spring:
  profiles:
    active: ${profile.active}
    
server:
  port: 8080
  connection-timeout: 10000
  tomcat:
    accept-count: 500
    max-connections: 500
    max-threads: 500
  context-path: /
  
#JPA 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
